gitHubLogin: "Sawthis"
gitHubToken: "prow/markdown-index/token"
gitName: "Wojciech Soltys"
gitEmail: "wojciech.soltys@sap.com"
skipPullRequest: false
gitHubOrg: "Sawthis"
gitHubRepo: "test-infra"
remoteName: "test-infra"
upstreamURLBase: "https://raw.githubusercontent.com/Sawthis/test-infra/main"
headBranchName: "test-infra-index-md-autobump"
foldersToFilter:
  - ".github"
  - ".githooks"
filesToFilter:
  - "/CODE_OF_CONDUCT.md"
  - "/CONTRIBUTING.md"
  - "/NOTICE.md"
  - "/README.md"
  - "/index.md"
  - "/docs/index.md"
  - "/test-inventory-integration.md"
