version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Sawthis/test-infra"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"